# tools/New-OtterNativeCoverage.ps1
#
# Writes docs/NATIVE_COMPILER_COVERAGE.md: every node kind in the frozen
# contract (Otter.Contract.psm1, enum NodeKind) and whether the experimental
# compiled backend handles it. Generated, never edited by hand:
#   - "compiled" kinds are the case labels in src/Otter.Compiler.Native.psm1;
#   - "partly" notes come from that module's $script:NativePartialKinds;
#   - everything else is "not yet".
# Run it after changing the compiler, and commit the result with the change.
#
#   powershell -NoProfile -File tools/New-OtterNativeCoverage.ps1 [-Check]
#
# -Check fails (exit 1) instead of writing when the committed list is stale.

param([switch]$Check)
$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
$contract = [System.IO.File]::ReadAllText((Join-Path $root 'Otter.Contract.psm1'))
$compiler = [System.IO.File]::ReadAllText((Join-Path $root 'src\Otter.Compiler.Native.psm1'))
$outPath = Join-Path $root 'docs\NATIVE_COMPILER_COVERAGE.md'

# Every NodeKind, in contract order.
$enumBody = [regex]::Match($contract, '(?s)enum NodeKind \{(.*?)\n\}').Groups[1].Value
$kinds = @([regex]::Matches($enumBody, '(?m)^\s+([A-Za-z]+)') | ForEach-Object { $_.Groups[1].Value } | Where-Object { $_ -ne 'Program' })

# Handled kinds: single-label cases and `{ $_ -in 'A', 'B' }` cases.
$handled = [System.Collections.Generic.HashSet[string]]::new()
foreach ($m in [regex]::Matches($compiler, "(?m)^\s{8}'([A-Za-z]+)' \{")) { [void]$handled.Add($m.Groups[1].Value) }
foreach ($m in [regex]::Matches($compiler, "\{ \`$_ -in ((?:'[A-Za-z]+'(?:, )?)+) \}")) {
    foreach ($k in [regex]::Matches($m.Groups[1].Value, "'([A-Za-z]+)'")) { [void]$handled.Add($k.Groups[1].Value) }
}

Import-Module (Join-Path $root 'src\Otter.Compiler.Native.psm1') -Force
$partial = Get-OtterNativePartialKinds
foreach ($k in $partial.Keys) {
    if (-not $handled.Contains($k)) { throw "NativePartialKinds names '$k', which the compiler does not handle." }
}
foreach ($k in $handled) {
    if ($kinds -notcontains $k) { throw "The compiler handles '$k', which is not a NodeKind in the contract." }
}

$compiledCount = @($kinds | Where-Object { $handled.Contains($_) -and -not $partial.Contains($_) }).Count
$partialCount = @($kinds | Where-Object { $partial.Contains($_) }).Count
$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add('# Native compiler coverage')
$lines.Add('')
$lines.Add('Generated by `tools/New-OtterNativeCoverage.ps1` from the contract and')
$lines.Add('`src/Otter.Compiler.Native.psm1`; do not edit by hand. A kind marked')
$lines.Add('"not yet" makes the compiled backend refuse the program, naming it, and the')
$lines.Add('program runs in the interpreter as before.')
$lines.Add('')
$lines.Add("**$compiledCount compiled, $partialCount partly, $($kinds.Count - $compiledCount - $partialCount) not yet, of $($kinds.Count) node kinds.**")
$lines.Add('')
$lines.Add('| Node kind | Compiled backend |')
$lines.Add('|---|---|')
foreach ($k in $kinds) {
    $status = if ($partial.Contains($k)) { "partly: $($partial[$k])" } elseif ($handled.Contains($k)) { 'compiled' } else { 'not yet' }
    $lines.Add("| $k | $status |")
}
$text = ($lines -join "`n") + "`n"

if ($Check) {
    $current = if (Test-Path -LiteralPath $outPath) { [System.IO.File]::ReadAllText($outPath) -replace "`r`n", "`n" } else { '' }
    if ($current -ne $text) { Write-Output 'docs/NATIVE_COMPILER_COVERAGE.md is stale: run tools/New-OtterNativeCoverage.ps1'; exit 1 }
    Write-Output 'docs/NATIVE_COMPILER_COVERAGE.md is current.'
    exit 0
}
[System.IO.File]::WriteAllText($outPath, $text, [System.Text.UTF8Encoding]::new($false))
Write-Output "Wrote $outPath ($compiledCount compiled, $partialCount partly, of $($kinds.Count))."
