<#
.SYNOPSIS
    Writes docs/OTTER_1_0_SURFACE_RECONCILIATION.md from the release-surface
    manifest and the derived contract-coverage evidence.

.DESCRIPTION
    The report is EVIDENCE for the Otter 1.0 public-boundary decision, not the
    decision. It is regenerated, never hand-edited, so it always agrees with
    release/otter-1.0-surface.json. Reads the manifest and coverage file only.
#>
[CmdletBinding()]
param(
    [string]$Manifest = 'release/otter-1.0-surface.json',
    [string]$Coverage = 'release/otter-1.0-contract-coverage.json',
    [string]$OutputPath = 'docs/OTTER_1_0_SURFACE_RECONCILIATION.md'
)

$ErrorActionPreference = 'Stop'
. "$PSScriptRoot\ReleaseSurface.Common.ps1"
$repoRoot = Get-OtterRepoRoot
function Resolve-RepoPath { param([string]$Path) if ([System.IO.Path]::IsPathRooted($Path)) { $Path } else { Join-Path $repoRoot $Path } }

$doc = [System.IO.File]::ReadAllText((Resolve-RepoPath $Manifest), [System.Text.Encoding]::UTF8) | ConvertFrom-Json
$cov = [System.IO.File]::ReadAllText((Resolve-RepoPath $Coverage), [System.Text.Encoding]::UTF8) | ConvertFrom-Json
$caps = @($doc.capabilities)

function Has-Conflict { param($Cap, [string]$Code) @($Cap.conflicts | Where-Object { $_.code -eq $Code }).Count -gt 0 }
function Cell { param([string]$Text) if ($null -eq $Text) { return '' }; return (($Text -replace '\|', '\|') -replace "`r?`n", ' ') }
function Join-Short { param($Items, [int]$Max = 4) $a = @($Items); if ($a.Count -eq 0) { return '-' }; $s = ($a | Select-Object -First $Max) -join ', '; if ($a.Count -gt $Max) { $s += " (+$($a.Count - $Max))" }; return $s }

$both = @($caps | Where-Object { $_.id -like 'R-*' -and (@($_.sources) -contains 'stdlib-boundary-doc') })
$reachOnly = @($caps | Where-Object { Has-Conflict $_ 'REACHABILITY_ONLY' })
$stdOnly = @($caps | Where-Object { Has-Conflict $_ 'STDLIB_DOC_ONLY' })
$implOnly = @($caps | Where-Object { Has-Conflict $_ 'IMPLEMENTATION_ONLY' })
$documented = @($caps | Where-Object { @($_.sources) -contains 'reachability-matrix' -or @($_.sources) -contains 'stdlib-boundary-doc' })
$docNoReach = @($documented | Where-Object { $_.productionReachability.reachable -ne $true })
$hostSpecific = @($caps | Where-Object { @($_.hints | Where-Object { $_ -like 'host-specific*' }).Count -gt 0 -or $_.hosts.browser.state -eq 'unsupported' })
$internalCandidates = @($caps | Where-Object { @($_.hints | Where-Object { $_ -like 'possibly-internal*' }).Count -gt 0 -or (Has-Conflict $_ 'RESERVED_MEMBER') })
$noProgram = @($caps | Where-Object { Has-Conflict $_ 'NO_PROGRAM_IN_CORPUS' })
$fullyEvidenced = @($caps | Where-Object {
    $_.productionReachability.reachable -eq $true -and @($_.tests.files).Count -gt 0 -and @($_.documentation.files).Count -gt 0 -and
    (@($_.contract.nodeKinds).Count -gt 0) -and $_.hosts.windowsPowerShell51.state -eq 'exercised' -and @($_.conflicts).Count -eq 0 })

$sb = New-Object System.Text.StringBuilder
function Line { param([string]$Text = '') [void]$script:sb.AppendLine($Text) }

Line '# Otter 1.0 Surface Reconciliation'
Line ''
Line '**Status: evidence for the public-boundary decision. This is not the decision.**'
Line 'Codex owns the Otter 1.0 public boundary. Every capability below is `candidate`'
Line 'with boundary `unresolved`. Nothing here is frozen, and nothing here claims'
Line 'that anything is public.'
Line ''
Line 'Generated by `tools/New-OtterSurfaceReconciliation.ps1` from'
Line '`release/otter-1.0-surface.json` and `release/otter-1.0-contract-coverage.json`.'
Line 'Regenerate rather than edit. Audit with `tools/Test-OtterReleaseSurface.ps1`.'
Line ''
Line '| | |'
Line '|---|---|'
Line "| Manifest seeded from commit | ``$($doc.manifest.seededFromCommit)`` |"
Line "| Gate 1 candidate SHA (nominated by Codex) | ``$($doc.manifest.candidateSha)`` - $(Cell $doc.manifest.candidateShaNote) |"
Line "| Contract SHA-256 | ``$($doc.manifest.contractSha256)`` |"
Line ''
Line '## Summary'
Line ''
Line '| Measure | Count |'
Line '|---|---:|'
Line "| Candidate capabilities in the manifest | $($caps.Count) |"
Line "| ... from the reachability matrix | $(@($caps | Where-Object { $_.id -like 'R-*' }).Count) |"
Line "| ... from STANDARD_LIBRARY.md only | $($stdOnly.Count) |"
Line "| ... from the contract only (in neither document) | $($implOnly.Count) |"
Line "| Fully evidenced (reachable, tested, documented, contract-linked, exercised on WinPS 5.1, no conflicts) | $($fullyEvidenced.Count) |"
Line "| With at least one documentation or evidence conflict | $(@($caps | Where-Object { @($_.conflicts).Count -gt 0 }).Count) |"
Line "| Without production-reachability evidence (reachable = null) | $(@($caps | Where-Object { $null -eq $_.productionReachability.reachable }).Count) |"
Line "| Boundary decided | 0 |"
Line ''
Line '"Fully evidenced" is a mechanical test of the manifest''s fields. It is not'
Line 'certification: no capability can be `certified` until its boundary is decided.'
Line ''

Line '## 1. In both documents'
Line ''
Line "$($both.Count) reachability-matrix rows have a matching phrase in STANDARD_LIBRARY.md."
Line ''
Line '| id | capability | area | nodes | suite case |'
Line '|---|---|---|---|---|'
foreach ($c in ($both | Sort-Object id)) { Line "| ``$($c.id)`` | $(Cell $c.publicName) | $(Cell $c.category) | $(Join-Short $c.contract.nodeKinds) | $(Join-Short $c.tests.cases 1) |" }
Line ''

Line '## 2. In STANDARD_LIBRARY_REACHABILITY.md only'
Line ''
Line "$($reachOnly.Count) rows. Each is production-reachable by the reachability suite but no STANDARD_LIBRARY.md phrase in the same area was matched to it. Several are probably the same capability described in different words (matching is by phrase, within area); they are listed so a reviewer can confirm."
Line ''
Line '| id | area | capability | syntax | nodes |'
Line '|---|---|---|---|---|'
foreach ($c in ($reachOnly | Sort-Object id)) { Line "| ``$($c.id)`` | $(Cell $c.category) | $(Cell $c.publicName) | ``$(Cell $c.syntaxOrForm)`` | $(Join-Short $c.contract.nodeKinds) |" }
Line ''

Line '## 3. In STANDARD_LIBRARY.md only'
Line ''
Line "$($stdOnly.Count) phrases from STANDARD_LIBRARY.md have no row in the reachability matrix, so no production-reachability evidence is recorded for them. Contract links are derived by word match and are hints only; ""none found"" usually means the phrase names a broad area (for example ""file locking"") rather than one operation."
Line ''
Line '| id | section | area | phrase | linked nodes (derived) | tested by a corpus program |'
Line '|---|---|---|---|---|---|'
foreach ($c in ($stdOnly | Sort-Object id)) {
    $tested = if (@($c.contract.nodeKinds).Count -eq 0) { 'unknown (no link)' } elseif (@($c.tests.files).Count -gt 0) { 'yes' } else { 'no' }
    $nodes = if (@($c.contract.nodeKinds).Count -gt 0) { Join-Short $c.contract.nodeKinds } else { 'none found' }
    Line "| ``$($c.id)`` | $(Cell $c.docSection) | $(Cell $c.category) | $(Cell $c.publicName) | $nodes | $tested |"
}
Line ''

Line '## 4. Implementation-backed, in neither document'
Line ''
Line "$($implOnly.Count) contract members are declared, parsed and dispatched but appear in neither standard-library document. Many are language constructs rather than library operations (see ""kind""); some are target-specific UI/web members covered by the web and UI documentation instead. Grouped by the contract's own section comment."
Line ''
$groups = $implOnly | Group-Object { if ($_.surfaceKind) { $_.surfaceKind } else { 'other' } } | Sort-Object Name
Line '| kind | count |'
Line '|---|---:|'
foreach ($g in $groups) { Line "| $($g.Name) | $($g.Count) |" }
Line ''
Line 'The section column is the nearest preceding section comment in `Otter.Contract.psm1`. Some members have no heading of their own and inherit one (for example `CopyFile`, `MoveFile` and `FileLocked` sit under the UI layout/show comment); "kind" corrects for the unambiguous cases by name.'
Line ''
Line '| kind | nearest contract section comment | members | no corpus program |'
Line '|---|---|---|---|'
foreach ($sec in ($implOnly | Group-Object { "$($_.surfaceKind)`t$($_.category)" } | Sort-Object Name)) {
    $parts = $sec.Name -split "`t"
    $members = @($sec.Group | ForEach-Object { $_.publicName })
    $cold = @($sec.Group | Where-Object { Has-Conflict $_ 'NO_PROGRAM_IN_CORPUS' } | ForEach-Object { $_.publicName })
    $section = if ([string]::IsNullOrWhiteSpace($parts[1])) { '(top of enum)' } else { $parts[1] }
    Line "| $($parts[0]) | $(Cell $section) | $(Join-Short $members 12) | $(Join-Short $cold 12) |"
}
Line ''

Line '## 5. Documented but lacking production-reachability evidence'
Line ''
Line "$($docNoReach.Count) documented capabilities (all from STANDARD_LIBRARY.md only). The manifest records ``reachable: null``, which means *not established by this evidence*, not *unreachable*. Many are exercised by focused suites; the reachability suite is the only place a production-entry claim per capability is currently recorded."
Line ''
Line "Of these, $(@($docNoReach | Where-Object { @($_.tests.files).Count -gt 0 }).Count) have at least one test or conformance program that parses to a linked contract member, and $(@($docNoReach | Where-Object { @($_.tests.files).Count -eq 0 }).Count) have none linked."
Line ''

Line '## 6. Host-specific'
Line ''
Line "$($hostSpecific.Count) capabilities carry a host-specific hint: the contract comment limits them to console/desktop or Windows, STANDARD_LIBRARY.md lists them under ""Target-specific library"", or the browser is recorded as unsupported. A hint is not a decision."
Line ''
Line '| id | capability | browser | why |'
Line '|---|---|---|---|'
foreach ($c in ($hostSpecific | Sort-Object id)) {
    $why = (@($c.hints | Where-Object { $_ -like 'host-specific*' }) -join '; ')
    if (-not $why) { $why = Cell $c.hosts.browser.evidence }
    Line "| ``$($c.id)`` | $(Cell $c.publicName) | $($c.hosts.browser.state) | $(Cell $why) |"
}
Line ''
Line 'Every capability records PowerShell 7 on Windows, Linux and macOS as `unverified`: the D120 CI'
Line 'matrix exercises the CLI and project commands on those hosts, not individual capabilities.'
Line ''

Line '## 7. Candidate internal-only'
Line ''
Line "$($internalCandidates.Count) members whose own contract comment says internal, reserved, legacy or deprecated, or which are declared reservations. Separately, $($noProgram.Count) contract-only members have no program anywhere in the test, conformance or example corpus that parses to them; those need a decision too (public with a test, or internal)."
Line ''
Line '| id | member | reason |'
Line '|---|---|---|'
foreach ($c in ($internalCandidates | Sort-Object id)) {
    $why = (@($c.hints | Where-Object { $_ -like 'possibly-internal*' }) + @($c.conflicts | Where-Object { $_.code -eq 'RESERVED_MEMBER' } | ForEach-Object { $_.detail })) -join '; '
    Line "| ``$($c.id)`` | $(Cell $c.publicName) | $(Cell $why) |"
}
Line ''
Line '| contract-only members with no corpus program |'
Line '|---|'
Line "| $(Join-Short ($noProgram | ForEach-Object { $_.publicName }) 60) |"
Line ''

Line '## 8. Cross-document conflicts'
Line ''
Line 'Verified by hand; each cites its evidence. Recorded, not resolved.'
Line ''
foreach ($dc in @($doc.documentConflicts)) {
    Line "### $($dc.id). $($dc.topic)"
    Line ''
    foreach ($cl in @($dc.claims)) { Line "* ``$($cl.file)``: $($cl.says)" }
    Line "* Evidence: $((@($dc.evidence) | ForEach-Object { '`' + $_ + '`' }) -join ', ')"
    Line "* Observation: $($dc.observation)"
    Line "* Decision: **pending**"
    Line ''
}

Line '## 9. Token, AST and diagnostic coverage'
Line ''
Line "Derived from ``release/otter-1.0-contract-coverage.json``. The corpus is every Otter program in ``conformance/``, ``examples/``, ``benchmarks/``, ``otter-docs/pages/`` and embedded in ``tests/*.Tests.ps1``: $($cov.derivedFrom.corpus.snippets) snippets, $($cov.derivedFrom.corpus.parsedPrograms) parsed by the real parser. A member counts as exercised when some program in that corpus produces it. That proves the pipeline builds it from real source, not that a test asserts its behavior."
Line ''
Line '| | Declared | Exercised by a corpus program | Wired, not exercised | Declared exception | Structural problem |'
Line '|---|---:|---:|---:|---:|---:|'
Line "| TokenKind | $($cov.summary.tokens.declared) | $($cov.summary.tokens.exercised) | $($cov.summary.tokens.wiredNotExercised) | $($cov.summary.tokens.declaredException) | $($cov.summary.tokens.unwired) |"
Line "| NodeKind | $($cov.summary.nodes.declared) | $($cov.summary.nodes.exercised) | $($cov.summary.nodes.wiredNotExercised) | $($cov.summary.nodes.declaredException) | $($cov.summary.nodes.problems) |"
Line ''
Line "Tokens wired but not produced by any corpus program: $(Join-Short (@($cov.tokens | Where-Object { $_.disposition -eq 'wired-not-exercised-by-corpus' } | ForEach-Object { $_.name })) 40)."
Line ''
Line "Nodes wired but not produced by any corpus program: $(Join-Short (@($cov.nodes | Where-Object { $_.disposition -eq 'wired-not-exercised-by-corpus' } | ForEach-Object { $_.name })) 40)."
Line ''
Line "Documentation linkage is weaker than code linkage: $(@($cov.nodes | Where-Object { @($_.documentation.files).Count -eq 0 }).Count) of $($cov.nodes.Count) nodes cite no SPEC-DECISIONS.md decision in their contract comment, and $(@($cov.tokens | Where-Object { @($_.documentation.files).Count -eq 0 }).Count) of $($cov.tokens.Count) tokens have neither a cited decision nor a keyword that appears in the grammar documents."
Line ''
Line '### Diagnostics'
Line ''
Line "$($cov.summary.diagnostics.callSites) error call sites were enumerated across the lexer, parser, interpreter, library, compiler, database, module, project, UI, web and desktop modules. For each, the longest fixed fragment of its message text was searched for in ``tests/``, ``conformance/manifest.json`` and the diagnostic and red-team reports."
Line ''
Line '| Evidence | Call sites |'
Line '|---|---:|'
Line "| Message fragment found in a test or diagnostic report | $($cov.summary.diagnostics.messageTextFoundInTests) |"
Line "| Fragment not found anywhere | $($cov.summary.diagnostics.messageTextNotFound) |"
Line "| Message built dynamically (no fixed text) | $($cov.summary.diagnostics.dynamicMessage) |"
Line "| Fixed text too short to match reliably | $($cov.summary.diagnostics.tooShortToMatch) |"
Line ''
Line 'Not finding a message fragment in a test does not mean the path is untested: many tests assert'
Line 'exit codes or a shorter phrase. It does mean the specific wording is not pinned by any test,'
Line 'which matters if diagnostic text is part of the 1.0 contract. Diagnostics have no stable'
Line 'identifiers in the source; ids here are `module#function#n` and change when code moves.'
Line ''

Line '## 10. Event system (pending contract decisions)'
Line ''
Line 'Current measured behavior is recorded per event-source capability (`eventSource` in the manifest). The'
Line 'questions below are unanswered; see `docs/OTTER_1_0_EVENT_LOOP_REVIEW.md`.'
Line ''
Line '| id | question | current behavior | decision |'
Line '|---|---|---|---|'
foreach ($q in @($doc.eventContract.questions)) { Line "| $($q.id) | $(Cell $q.question) | $(Cell $q.currentBehavior) | pending |" }
Line ''

Line '## What this report does not do'
Line ''
Line '* It does not decide what is public, and no capability is marked certified.'
Line '* It does not change any source, grammar, runtime behavior or other document.'
Line '* Links between documentation phrases and contract members are derived by word matching'
Line '  and labelled as such in the manifest; they are for a reviewer to confirm, not facts.'

$out = Resolve-RepoPath $OutputPath
[System.IO.File]::WriteAllText($out, $sb.ToString(), [System.Text.UTF8Encoding]::new($false))
Write-Output "Written: $out"
Write-Output ("both: {0}; reachability only: {1}; stdlib doc only: {2}; implementation only: {3}; documented without reachability: {4}; host-specific: {5}; internal candidates: {6}; fully evidenced: {7}" -f $both.Count, $reachOnly.Count, $stdOnly.Count, $implOnly.Count, $docNoReach.Count, $hostSpecific.Count, $internalCandidates.Count, $fullyEvidenced.Count)
